# Write your MySQL query statement below
SELECT QUERY_NAME, ROUND(SUM(RATING/POSITION)/COUNT(*),2) AS QUALITY, ROUND(COUNT(IF(RATING < 3, 1, NULL))/COUNT(*)*100,2) AS POOR_QUERY_PERCENTAGE
FROM (
SELECT QUERY_NAME, RESULT, POSITION, RATING, RATING/POSITION
FROM QUERIES  ) TEMP 
GROUP BY QUERY_NAME;